SemiPhysBuildingSim-v0:
  env_wrapper:
# 先添加历史观测包装器，再添加帧跳包装器，这样可以确保每个时间步都有完整的历史观测，而不是只跳帧而不记录历史。
    - rl_zoo3.wrappers.ObsHistoryWrapper:
        horizon: 5
    - rl_zoo3.wrappers.FrameSkip:
        skip: 5
  n_timesteps: !!float 5e5
  policy: 'MlpPolicy'
  learning_rate: !!float 2.3e-3
  batch_size: 64
  buffer_size: 100000
  learning_starts: 1000
  gamma: 0.99
  target_update_interval: 10
  train_freq: 256
  gradient_steps: 128
  exploration_fraction: 0.16
  exploration_final_eps: 0.04
  policy_kwargs: "dict(net_arch=[256, 256],
                         hypergraph=[[0,], [1,], [2,], [3, 4, 5,], [6,]])"
